version: '3.8'
services:
  
  # Application
  app:
      build:
          dockerfile: app.prod.dockerfile
      
  # Web Server
  webnginx:
      build:
          dockerfile: web.prod.dockerfile
      hostname: webnginx
      container_name: webnginx
      restart: unless-stopped
      ports:
        - 80:80
      networks:
        static-network:
          ipv4_address: 172.19.0.5
      labels:
        - "traefik.enable=true" # Enable Traefik to route traffic to this container
        - "traefik.http.routers.webnginx.rule=Host(`STACKHERO_DOCKER_HOST`)" # Defined host
        - "traefik.http.routers.webnginx.tls.certresolver=letsencrypt" # Use "letsencrypt" as TLS cert resolver

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.19.0.0/12