version: '3.8'
services:
  
  # Application
  app:
      build:
          context: .
      working_dir: /var/www

  # Web Server
  web:
      build:
          context: .
      working_dir: /var/www
      
      depends_on:
          - "app"
      ports:
          - 80:80