version: '3.8'
services:
  
  # Application
  app:
      build:
          dockerfile: app.prod.dockerfile
      
  # Web Server
  web:
      build:
          dockerfile: web.prod.dockerfile
      hostname: web
      container_name: web
      restart: unless-stopped
      ports:
        - 80:80
        - 443:443
      labels:
        - "traefik.enable=true" # Enable Traefik to route traffic to this container
        - "traefik.http.routers.web.rule=HostRegexp(`marblemetrics.com`)" # Defined host
        - "traefik.http.routers.web.tls.certresolver=letsencrypt" # Use "letsencrypt" as TLS cert resolver