version: '3.8'
services:
    
    # Application
    app:
        build:
            context: .
            dockerfile: app.dockerfile
        working_dir: /var/www
    # Web Server
    web:
        build:
            context: .
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 80:80
        labels:
          - "traefik.enable=true" # Enable Traefik to route traffic to this container
          - "traefik.http.routers.test.rule=HostRegexp(`hw8cnq.stackhero-network.com`)" # Defined host
          - "traefik.http.routers.test.tls.certresolver=letsencrypt" # Use "letsencrypt" as TLS cert resolver