on: push
name: Build Prod
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-fpm

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: list directory
        run: |
          ls
          pwd
          echo ${{ github.workspace }}
      - name: Check the content of the output log
        run: |
          mkdir -p ${{ github.workspace }}
          touch ${{ github.workspace }}/output.log
      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          command: install
          dev: no
          args: --working-dir ./src
      - name: Install node dependencies
        working-directory: ./src
        run: |
          npm install;
      - name: Build vite
        run: |
          npm run build;