on:
  push:
    branches: [ master ]
name: Build Staging
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-action